# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_facebookprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofile',
            name='level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='times_called',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
