# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-24 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_remove_facebookprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='facebookprofile',
            name='score',
        ),
        migrations.RemoveField(
            model_name='facebookprofile',
            name='times_called',
        ),
    ]
