# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-24 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20161224_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testuserprofile',
            old_name='website',
            new_name='webpull',
        ),
        migrations.AddField(
            model_name='testuserprofile',
            name='year_formed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testuserprofile',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
