# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_auto_20161224_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testuserprofile',
            old_name='webpull',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='testuserprofile',
            name='year_formed',
        ),
        migrations.AlterField(
            model_name='testuserprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
